### ISSUE TITLE
deleteItem(...).where(...) does not seem to work

### ISSUE THREAD

**Issue by googley42** [zio/zio-dynamodb#112]
Investigate why a `where` clause added on to a deleteItem does not seem to work. It may be worth adding a test for this in the LiveSpec IT test

**Comment by nhyne** [comment]
Do you have a specific example of this that is failing? I added a test to the LiveSpec but it's passing currently without any code changes.

**Comment by googley42** [comment]
I have added a test to my branch here https://github.com/zio/zio-dynamodb/blob/ro_for_pe_type_param_2/dynamodb/src/it/scala/zio/dynamodb/LiveSpec.scala#L157-L173 to reproduce the behaviour.
```scala
        testM("delete item with where clause") {
          withDefaultTable { tableName =>
            for {
              _     <- deleteItem(tableName, pk(aviItem))
                         .where(
                           ConditionExpression.Equals(
                             ConditionExpression.Operand.ProjectionExpressionOperand($(number)),
                             ConditionExpression.Operand.ValueOperand(
                               AttributeValue(42)
                             ) // this should fail delete as number is 1
                           )
                         )
                         .execute
              after <- getItem(tableName, pk(aviItem)).execute
            } yield assert(after)(isNone)
          }
        },
```

**Comment by nhyne** [comment]
After doing some investigation I believe this is due to the `DeleteItem` request being turned into a `BatchWriteItem`, which does not have condition expressions. We may need to update the auto-batching to check to see if there is a request that contains a condition expression.

**Comment by googley42** [comment]
Many thanks for investigating this. I will try and have a look at BatchWriteItem later on in the week

**Comment by googley42** [comment]
that would be great
