### ISSUE TITLE
Replace EitherUtil  with usage of zio-prelude functions

### ISSUE THREAD

**Issue by googley42** [zio/zio-dynamodb#150]
Very early on it was decided to minimise the dependencies we pushed on users so EitherUtil was created. However the latest version of ZIO 2.x zio-aws puts `zio-prelude` on the classpath so we should use that.

EitherUtil.forEach gets replaced by zio-preludes `forEach` and EitherUtil.collectAll gets replaced by zio-preludes `flip`

**Comment by morozovivan95** [comment]
I would like to work on this

**Comment by googley42** [comment]
we probably should add `zio-prelude` as an explicit dependency, rather than rely on it transitively

**Comment by googley42** [comment]
[closed by ](https://github.com/zio/zio-dynamodb/pull/190)
