### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by ioleo** [zio/zio-dynamodb#171]
Would love to see Scala 3 supported.

**Comment by googley42** [comment]
Now would be good time to do this as the type safe API is feature complete

**Comment by notericcartman** [comment]
https://mvnrepository.com/artifact/dev.zio/zio-dynamodb

@ioleo looks like it is published for scala 3 ?

**Comment by ioleo** [comment]
Yes, we worked on that with @googley42 . This issue is solved
