### ISSUE TITLE
AttributeDefinition in DynamoDBQuery.createTable has private access

### ISSUE THREAD

**Issue by stanislav-chetvertkov** [zio/zio-dynamodb#354]
I'm trying to run a snippet to create a table similar to https://github.com/zio/zio-dynamodb/blob/series/2.x/examples/src/main/scala/zio/dynamodb/examples/TableExamples.scala
but getting a compiler error
```
object AttributeDefinition in package dynamodb cannot be accessed in package zio.dynamodb
[error] import zio.dynamodb.AttributeDefinition.{attrDefnNumber, attrDefnString}
```
not sure if DynamoDBQuery.createTable meant to be used as internal api but I couldn't find other ways to access this functionality

**Comment by googley42** [comment]
hi @stanislav-chetvertkov I am having trouble reproducing this compile error - I have cut and pasted the example in a standalone sbt project without any compile errors. Would it be possible to create a new minimal public GitHub repo that replicated your problem and post the URL here pls?

**Comment by stanislav-chetvertkov** [comment]
Hi @googley42 ,
The issue seems to appear only in scala 2.12, initially, I've created a minimal sbt project to reproduce it https://github.com/stanislav-chetvertkov/zio-dynamodb-reproduce-error and the compilation worked but after changing the scala version from 2.13 to 2.12 I got the same error again

**Comment by googley42** [comment]
hi @stanislav-chetvertkov,
Many thanks for posting the reproducer. I will have a look at this over the holiday period. BTW do you explicitly want to use Scala 2.12 in your project that uses ZIO DynamoDB? If so is it an external restriction eg 2.12 is used at work?

**Comment by googley42** [comment]
hi @stanislav-chetvertkov I think I have fixed the issue. Could you pls test the latest snapshot from master in your reproducer and let me know the outcome - you will need to add the line `resolvers += Resolver.sonatypeRepo("snapshots")` to your `buid.sbt`
