### ISSUE TITLE
`ProjectionExpression` Parser - expression substitution mechanism

### ISSUE THREAD

**Issue by googley42** [zio/zio-dynamodb#40]
The AWS DDB API provides an expression substitution mechanism for avoiding clashes with key words etc etc.
The same facility is required for the `ProjectionExpression` parser

**Comment by paul-danilin-moia** [comment]
Hi, currently this fails on a `ttl` attribute. 

Test suite to check a fix should look like this:
```scala
final case class Record(
    ttl: Option[Long]
)
object Record {
  implicit val schema = DeriveSchema.gen[Record]
  val (ttl)           = ProjectionExpression.accessors[Record]
}
...

suite("attribute name 'ttl")(
  test("should be successfully handled through schema derivation") {
    withDefaultTable { tableName =>
      val query = DynamoDBQuery
        .scanAll[Record](tableName)
        .filter(Record.ttl.notExists)
      query.execute.flatMap(_.runDrain).exit.map { result =>
        assert(result)(succeeds(isUnit))
      }
    }
  },
  test("should be successfully handled through $ syntax") {
    withDefaultTable { tableName =>
      val query = DynamoDBQuery
        .scanAll[Record](tableName)
        .filter($("ttl").notExists)
      query.execute.flatMap(_.runDrain).exit.map { result =>
        assert(result)(succeeds(isUnit))
      }
    }
  }
)
```
Do you have any plans for the issue?

**Comment by googley42** [comment]
hi @paul-danilin-moia, many thanks for reporting this and the examples - I was able to reproduce it. Out of curiosity do you use the low level API directly (eg `$` function) ?

A work around for moment if you only use the high level API only and a greenfield DDB database is to use the `@fieldName` annotation to avoid reserved word clashes.
```scala
final case class Record(
  email: String,
  @fieldName("alt_ttl") ttl: Option[Long]
)
```
I will have a look at this issue next
Thanks

**Comment by paul-danilin-moia** [comment]
I tried to do it with the `accessors` macros as it is done in [this example](https://github.com/zio/zio-dynamodb/blob/series/2.x/examples/src/main/scala/zio/dynamodb/examples/model/Student.scala#L44-L57) but the compilation would think that the constants defined within `val (???)` are of type `Any` so I gave up and had to use `$`. 
What does the `@fieldName` do? The attribute name in my dynamo table is called literally `ttl` and it would be hard to change it on this stage.

**Comment by googley42** [comment]
> but the compilation would think that the constants defined within val (???) are of type Any

Are you using Intellij? If so its built in compiler reports false negatives like this. Did you try to compile your example using `DeriveSchema.gen` on the command line using `sbt` - I am fairly sure it would work. VSCode + Metals does not suffer from this problem and is able to report types reliably
> What does the `@fieldName` do?

 this annotation name was introduced in the latest version (previously it was the `@id` annotation) and changes the name of the attribute stored in DynamoDB - hence this is a workaround provided you have no legacy data - unfortunately it sounds like you do have legacy data so would need a proper fix

**Comment by paul-danilin-moia** [comment]
> Are you using Intellij?

I am using Intellij and tried both its nested compiler and running `sbt compile` from cli. In both of the cases the compilation error was the same. I couldn't reproduce it in your repository though so I gave up.

> unfortunately it sounds like you do have legacy data so would need a proper fix

Yes, this is precisely my case, I have some data in the table already and changing the attribute name is not an option.

**Comment by googley42** [comment]
> sbt compile from cli. In both of the cases the compilation error was the same

sorry to hear that. In order to debug the `Any` problem is there a chance you could create a skinny sbt project with a small reproducer class - you would only need the `DeriveSchema.gen` and `ProjectionExpression.accessors` model stuff (no need to wire up a dynamodb client for a query) - from that I could check the versions etc of your libs etc - maybe you could use https://scastie.scala-lang.org/

**Comment by googley42** [comment]
@paul-danilin-moia I found _a_ reproducer for you `Any` macro problem

When I did auto complete in Intellij for `val schema` it gave `implicit val schema: Schema[ExpressionAttrNames]` which is wrong and will fail when doing an sbt compile  (note type completion with VSCode gives `: Schema.CaseClass3.WithFields["id","num","ttl",String,Int,Option[Long],ExpressionAttrNames]`)  eg:
```scala
  final case class ExpressionAttrNames(id: String, num: Int, ttl: Option[Long])
  object ExpressionAttrNames {
    implicit val schema: Schema[ExpressionAttrNames] = DeriveSchema.gen[ExpressionAttrNames]
    // id, num, ttl have type Any
    val (id, num, ttl)  = ProjectionExpression.accessors[ExpressionAttrNames]
  }
```
If you leave out the type the type it infers OK and sbt compile works
```scala
  final case class ExpressionAttrNames(id: String, num: Int, ttl: Option[Long])
  object ExpressionAttrNames {
    implicit val schema = DeriveSchema.gen[ExpressionAttrNames]
    // id, num, ttl have correct types
    val (id, num, ttl)  = ProjectionExpression.accessors[ExpressionAttrNames]
  }
```
Also I am working on the fix for the attribute name substitution problem. A complete example of the above can be found on this branch https://github.com/zio/zio-dynamodb/blob/series/2.x_pe_sbst/dynamodb/src/it/scala/zio/dynamodb/LiveSpec.scala#L163-L196

**Comment by googley42** [comment]
@paul-danilin-moia I have just created the [`2.0.7`](https://github.com/zio/zio-dynamodb/releases/tag/v0.2.7) release that fixes this issue. Can you please give it a go when you have the chance and let me know how you get on - there are example in [`LiveSpec.scala`](https://github.com/zio/zio-dynamodb/blob/series/2.x/dynamodb/src/it/scala/zio/dynamodb/LiveSpec.scala#L173-L182)

**Comment by paul-danilin-moia** [comment]
I've checked and it works for me now, both for conditional expressions and updates.
Thank you!

**Comment by paul-danilin-moia** [comment]
By the way, removing the `schema` type as you said, helped with the accessors.

**Comment by googley42** [comment]
@paul-danilin-moia great to hear! Btw are you able to use the high level type safe API now?

**Comment by paul-danilin-moia** [comment]
Do you mean the macro `ProjectionExpression.accessors[Record]`? 
If so, yes, it has worked out good!

**Comment by googley42** [comment]
fixed by https://github.com/zio/zio-dynamodb/pull/163
