### ISSUE TITLE
Upgrade to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [zio/zio-dynamodb#53]
ZIO 2.0 is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala
We highly recommend starting with that, and then working through any remaining compilation errors :)

To assist with the rest of the migration, we have created this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

**Comment by adrianfilip** [comment]
The migration guide is now at this page:  https://zio.dev/next/howto/migrate/zio-2.x-migration-guide/

**Comment by adrianfilip** [comment]
I am picking this one.

**Comment by adrianfilip** [comment]
The migration rule here is a bit different than the one in the migration guide at the time of writing this. 
```sbt "scalafixEnable; scalafixAll github:swoogles/zio/Zio2Upgrade?sha=crossbuild_scalafix_2"```

**Comment by swoogles** [comment]
@adrianfilip 
It was merged to the main ZIO repo this morning, so the existing rule link should be valid again 🙂

**Comment by adrianfilip** [comment]
Dependencies:

- [ ] zio-config
- [ ] zio-aws

**Comment by adrianfilip** [comment]
I will continue as the dependencies are released.

**Comment by googley42** [comment]
@adrianfilip thanks for picking this one up. How do other projects handle maintaining 2 different versions ie version 1.X and 2.X - - do they use 2 different branches? Also a heads up that this project is only just coming out of experimental stage and the API is quite volatile ATM.

**Comment by adrianfilip** [comment]
@googley42 Yes, they use a separate branch  (e.g.: https://github.com/zio/zio-nio/tree/series/2.x)

**Comment by googley42** [comment]
@adrianfilip I have removed the `zio-config` dependency as it was not being used - that leaves just `zio-aws` I believe that we are waiting on for a 2.x release

**Comment by swoogles** [comment]
> @adrianfilip I have removed the `zio-config` dependency as it was not being used - that leaves just `zio-aws` I believe that we are waiting on for a 2.x release 

Zio-aws has been updated for the latest RC :)

 "dev.zio" %% "zio-aws-core" % "5.17.130.2" 

This page will track which libraries are on the latest version of ZIO-
https://zio-ecosystem.herokuapp.com/

**Comment by adrianfilip** [comment]
I will try to make the update this week-end, everything seems to be available now.

**Comment by googley42** [comment]
there are a couple of places where we use `ZStream.aggregateAsync` - I noticed a bug in this by chance in `v2.0.0_RC2` and reported it. Looks like its been fixed by Daniel here https://github.com/zio/zio/issues/6395 in the 2.0 branch.

**Comment by adrianfilip** [comment]
I'll double check that. I think I will have a PR today or tomorrow.

**Comment by googley42** [comment]
awesome - no rush!

**Comment by adrianfilip** [comment]
One remaining failing test. 
Should be fixed by this PR in zio-schema - https://github.com/zio/zio-schema/pull/205

**Comment by mbbx6spp** [comment]
@adrianfilip are you still working on the PR for this? Is there anything I can do to assist? Thanks.

**Comment by adrianfilip** [comment]
@mbbx6spp yes. Will continue today. I see the zio-schema PR was merged so the last failing test should pass. If anything else comes up I will let you know. Thanks.

**Comment by adrianfilip** [comment]
@mbbx6spp 

I updated to latest schema and it introduces 2 new types that need encoder & decoder. I will look into that the following days. If that's something that's in your ballpark feel free to make a PR for it (https://github.com/adrianfilip/zio-dynamodb/tree/53_zio2)

**Comment by mbbx6spp** [comment]
@adrianfilip thanks, I will take a look this evening!

**Comment by adrianfilip** [comment]
Updated the decoder/encoder implementation.
Some tests are not compiling because zio-aws is not updated to zio2 rc4. Following this https://github.com/zio/zio-aws/pull/775

**Comment by adrianfilip** [comment]
https://github.com/zio/zio-dynamodb/pull/99

**Comment by googley42** [comment]
closed by https://github.com/zio/zio-dynamodb/pull/99

**Comment by googley42** [comment]
reopened as this is an ongoing process with multiple releases

**Comment by googley42** [comment]
closed by multiple PR and finally by making the `series/2.x` branch the default
