### ISSUE TITLE
the live DynamoDBExecutor implementation needs to handle unprocessed Items for batch ops

### ISSUE THREAD

**Issue by googley42** [zio/zio-dynamodb#64]
the live DynamoDBExecutor implementation need to handle UnprocessedKeys for BatchGetItem and UnprocessedItems for BatchWriteItem.

From the AWS docs:
> If DynamoDB returns any unprocessed items, you should retry the batch operation on those items. However, we strongly recommend that you use an exponential backoff algorithm. If you retry the batch operation immediately, the underlying read or write requests can still fail due to throttling on the individual tables. If you delay the batch operation using exponential backoff, the individual requests in the batch are much more likely to succeed.

**Comment by nhyne** [comment]
Closed as a part of [this PR](https://github.com/zio/zio-dynamodb/pull/69)
